    name: flutter_app
    description: A new Flutter application.

    # The following line prevents the package from being accidentally published to
    # pub.dev using `pub publish`. This is preferred for private packages.
    publish_to: 'none' # Remove this line if you wish to publish to pub.dev

    # The following defines the version and build number for your application.
    # A version number is three numbers separated by dots, like 1.2.43
    # followed by an optional build number separated by a +.
    # Both the version and the builder number may be overridden in flutter
    # build by specifying --build-name and --build-number, respectively.
    # In Android, build-name is used as versionName while build-number used as versionCode.
    # Read more about Android versioning at https://developer.android.com/studio/publish/versioning
    # In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
    # Read more about iOS versioning at
    # https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
    version: 1.0.0+1

    environment:
      sdk: ">=2.7.0 <3.0.0"

    dependencies:
      flutter:
        sdk: flutter

      url_launcher: ^4.0.1

      http: ^0.12.0+2



      # The following adds the Cupertino Icons font to your application.
      # Use with the CupertinoIcons class for iOS style icons.
      cupertino_icons: ^1.0.0
      shared_preferences: ^0.4.2
      flutter_screenutil: ^4.0.2+3
      font_awesome_flutter: '>= 4.7.0'
      flutter_swiper: ^1.1.6
      fluttertoast: ^7.1.6
      rxdart: ^0.23.1
      flutter_bloc: ^6.0.6
      sp_util: ^1.0.1
      oktoast: ^2.3.2
      flutter_smart_dialog: ^1.2.6
      cached_network_image: ^2.5.0
      flutter_picker:
        git: git://github.com/jingfighting0628/flutter_picker.git
      date_format: ^1.0.9
      pull_to_refresh: 1.1.6
      flukit: ^1.0.2
    dev_dependencies:
      flutter_test:
        sdk: flutter

    # For information on the generic Dart part of this file, see the
    # following page: https://dart.dev/tools/pub/pubspec

    # The following section is specific to Flutter.
    flutter:

      # The following line ensures that the Material Icons font is
      # included with your application, so that you can use the icons in
      # the material Icons class.
      uses-material-design: true

      # To add assets to your application, add an assets section, like this:
      assets:
         - images/1.jpg
         - images/LoginLogo.png
         - images/login.png
         - LoginBtnBg.png
         - images/Img_296.png
         - images/Img_294.png
         - images/Img_363.png
         - images/Img_274.png
         - images/Img_275.png
         - images/Img_300.png
         - images/Img_344.png
         - images/more.png
         - images/home.png
         - images/home_selected.png
         - images/work.png
         - images/work_selected.png
         - images/project.png
         - images/project_selected.png
         - images/Mine.png
         - images/Mine_selected.png
         - images/notice.png
         - images/close.png
         - images/plus1.png
         - images/floatingActionImg.png


      # An image asset can refer to one or more resolution-specific "variants", see
      # https://flutter.dev/assets-and-images/#resolution-aware.

      # For details regarding adding assets from package dependencies, see
      # https://flutter.dev/assets-and-images/#from-packages

      # To add custom fonts to your application, add a fonts section here,
      # in this "flutter" section. Each entry in this list should have a
      # "family" key with the font family name, and a "fonts" key with a
      # list giving the asset and other descriptors for the font. For
      # example:
      # fonts:
      #   - family: Schyler
      #     fonts:
      #       - asset: fonts/Schyler-Regular.ttf
      #       - asset: fonts/Schyler-Italic.ttf
      #         style: italic
      #   - family: Trajan Pro
      #     fonts:
      #       - asset: fonts/TrajanPro.ttf
      #       - asset: fonts/TrajanPro_Bold.ttf
      #         weight: 700
      #
      # For details regarding fonts from package dependencies,
      # see https://flutter.dev/custom-fonts/#from-packages
